{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        args:
        - --provider={{ .Values.config.provider }}
        - --authenticated-emails-file=/etc/oauth2-proxy/emails.txt
        - --client-id=$(CLIENT_ID)
        - --client-secret=$(CLIENT_SECRET)
        - --cookie-secret=$(COOKIE_SECRET)
        - --redirect-url={{ .Values.config.redirectUrl }}
        - --cookie-secure={{ .Values.config.cookieSecure }}
        - --http-address={{ .Values.config.httpAddress }}
        - --set-authorization-header={{ .Values.config.setAuthorizationHeader }}
        - --pass-basic-auth={{ .Values.config.passBasicAuth }}
        - --basic-auth-password={{ .Values.config.basicAuthPassword }}
        - --reverse-proxy={{ .Values.config.reverseProxy }}
        - --ssl-redirect={{ .Values.config.sslRedirect }}
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-config
              key: client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-config
              key: client-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-config
              key: cookie-secret
        volumeMounts:
        - name: emails
          mountPath: /etc/oauth2-proxy
        ports:
        - containerPort: 4180
      volumes:
      - name: emails
        configMap:
          name: oauth2-proxy-emails
{{- end }}
