{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-config
  labels:
    app: oauth2-proxy
stringData:
  client-id: {{ .Values.config.clientId }}
  client-secret: {{ .Values.config.clientSecret }}
  cookie-secret: {{ .Values.config.cookieSecret }}
{{- end }}
