apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "debian-desktop.fullname" . }}
  labels:
    {{- include "debian-desktop.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "debian-desktop.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "debian-desktop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "debian-desktop.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: fix-permissions
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        securityContext:
          runAsUser: 0
        command: ["/bin/sh", "-c"]
        args:
        - chown -R 1000:1000 /home/{{ .Values.env.user }}
        volumeMounts:
        - name: config
          mountPath: /home/{{ .Values.env.user }}
      containers:
      - name: nginx-auth-injector
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-conf
          mountPath: /usr/share/novnc/logout.html
          subPath: logout.html
        - name: nginx-conf
          mountPath: /usr/share/novnc/app/images/logout.svg
          subPath: logout.svg
      - name: desktop
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: TZ
          value: {{ .Values.env.tz | quote }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 6901
          name: https
        - containerPort: 6902
          name: audio
        volumeMounts:
        - name: config
          mountPath: /home/{{ .Values.env.user }}
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: config
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "debian-desktop.fullname" . }}-config
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: nginx-conf
        configMap:
          name: {{ include "debian-desktop.fullname" . }}-nginx
